# NOTE: This file relies on the image built by the standard Dockerfile
# under release/ and that its name is 'mctrace'. Use 'build.sh' to build
# both the source image and this one.
FROM mctrace AS source

# The final image will be based on ubuntu
FROM ubuntu:22.04 as base

# Environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV MCTRACE_BIN_PATH=/mctrace-bin

# Install packages
RUN \
  apt-get update && \
  apt-get upgrade -y

# Copy the minimal amount of files we need to get mctrace running
COPY --from=source ${MCTRACE_BIN_PATH}/mctrace ${MCTRACE_BIN_PATH}/mctrace

COPY --from=source /lib/x86_64-linux-gnu/libLLVM-12.so.1 /lib/x86_64-linux-gnu/libLLVM-12.so.1
COPY --from=source /lib/x86_64-linux-gnu/libedit.so.2 /lib/x86_64-linux-gnu/libedit.so.2
COPY --from=source /lib/x86_64-linux-gnu/libxml2.so.2 /lib/x86_64-linux-gnu/libxml2.so.2
COPY --from=source /lib/x86_64-linux-gnu/libbsd.so.0 /lib/x86_64-linux-gnu/libbsd.so.0
COPY --from=source /lib/x86_64-linux-gnu/libicuuc.so.70 /lib/x86_64-linux-gnu/libicuuc.so.70
COPY --from=source /lib/x86_64-linux-gnu/libmd.so.0 /lib/x86_64-linux-gnu/libmd.so.0
COPY --from=source /lib/x86_64-linux-gnu/libicudata.so.70 /lib/x86_64-linux-gnu/libicudata.so.70

# Adjust paths to bring useful tools on to the path
ENV PATH=${PATH}:${MCTRACE_BIN_PATH}
ENV DOCKER=1

# Set mctrace command as the entrypoint
ENTRYPOINT [ "mctrace" ]
